### ISSUE TITLE
chain.upper() issue

### ISSUE THREAD

**Issue by sehooni** [johnnytam100/pdb2uniprot#2]
hi
thank you for great code for assigning the PDB id with Uniprot id.

however, I want to tell you something to change.
In chain id, there are some lower chain in PDB.

So I want to advice to change the code from 'chain.upper()' to 'chain' below.
It will be more accurately operate for other cases. :)

https://github.com/johnnytam100/pdb2uniprot/blob/b9b5ac585aaccdd4402c6c960085e36a064fb1d3/pdb2uniprot_tam.py#L75C10-L75C53

**Comment by johnnytam100** [comment]
didn't notice that before and now changed! Thanks!
